  name: JMeter Test
  run-name: ${{ github.actor }} is learning GitHub Actions
  on:
    push:
    schedule:
    # * is a special character in YAML so you have to quote this string
      - cron:  '4,15 13 * * *'
  jobs:
    jmeter_job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Run JMeter Tests
          uses: QAInsights/PerfAction@v3.1
          with:
            test-plan-path: './DemoBlaze-1.0.0.jmx'
            args: ''
            
        - name: Upload Results
          uses: actions/upload-artifact@v2
          with:
            name: jmeter-results
            path: result.jtl
            
        - name: Analyze Results with Latency Lingo
          uses: latency-lingo/github-action@v0.0.2
          with:
            api-key: ${{secrets.LATENCY_LINGO_API_KEY}}
            file: result.jtl
            label: Checkout Flow Automated Test Plan
            format: jmeter
